FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc curl \ 
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
# RUN python train_models.py

ENV FLASK_ENV=development
ENV FLASK_DUBUG=1
ENV PYTHONUNBUFFERED=1
EXPOSE 5000

CMD ["python", "app.py"]