services:
  - type: web
    name: predictive-pulse
    runtime: python
    buildCommand: pip install -r requirements.txt && python train_models.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
    plan: free
